### DISCUSSION TITLE
Moving secrets from management cluster to target

### DISCUSSION THREAD

**Discussion by Stringls** [syself/cluster-api-provider-hetzner#840] [General]
Hi! I have a use case when I need to move some secrets from management cluster to workload clusters. I discovered a label `clusterctl.cluster.x-k8s.io/move` which you use to move `hetzner` secret to `kube-system` namespace onto workload cluster. I am not able to find code that does this. Could you please explain is it possible to move any secrets from management cluster to workload clusters using this label or it's being defined on provider level and I can move only secrets you defined in CAPH controller? Thanks

**Comment by guettli** [comment]
This "magic move" is part of cluster API. 

Here are the details:

https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move

You can move other secrets the same way. 

In the Makefile you find an example "patch" command.

Does this answers your question?

**Reply by Stringls** [reply]
@guettli Thank you for your quick response.
I tried to attach the label to other secrets that I create during cluster creation (alongside with cluster) but they are not being moved to the target cluster. The secret's manifest looks like this
```yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/managed-by: hashicorp-vso
    app.kubernetes.io/name: vault-secrets-operator
    clusterctl.cluster.x-k8s.io/move: ""
  name: vault-token
  namespace: capi-poc-clusterctl-move-secrets-cluster
  ownerReferences:
  - apiVersion: secrets.hashicorp.com/v1alpha1
    kind: VaultStaticSecret
    name: vault-kv-vault-token
type: Opaque
```

One interesting thing. `hetzner` secret gets a special label called `caph.environment=owned`. It does this function https://github.com/syself/cluster-api-provider-hetzner/blob/28c897e16c9ce9f05fd2eee98f695a6ee744caff/pkg/secrets/label.go#L36
but it does not do it to other secrets e.g. `robot-ssh` that you patch as well. It's not moved to the target cluster and does not have this label.

So my questions are:
1. If I move my secret to the target (workload) cluster, it's being deployed in the default namespace or in the namespace of the secret?
  1. `hetzner` secret is being deployed to `kube-system` namespace but I do not specify it anywhere.
2. What's wrong with my secret? Why it's not being moved?
3. Why `robot-ssh` secret it not being moved as well?
4. Does this label is crucial and I need it for controllers to move my secret to the target cluster?
