### ISSUE TITLE
MachineDeployment using HCloudMachines never gets Ready

### ISSUE THREAD

**Issue by jnummelin** [syself/cluster-api-provider-hetzner#1055]
/kind bug

**What steps did you take and what happened:**
I'm running some worker nodes using MachineDeployment and related templates.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: as-hetzner-md
  namespace: autoscaler-test
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
  labels:
    nodepool: hetzner-worker-small
    cluster.x-k8s.io/cluster-name: autoscaler-test
spec:
  clusterName: autoscaler-test
  selector:
    matchLabels:
      nodepool: hetzner-worker-small
      cluster.x-k8s.io/cluster-name: autoscaler-test
  template:
    metadata:
      labels:
        nodepool: hetzner-worker-small
        cluster.x-k8s.io/cluster-name: autoscaler-test
    spec:
      version: v1.28.3
      clusterName: autoscaler-test
      failureDomain: fsn1
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: as-hetzner-mc
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: as-hetzner-mt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: as-hetzner-mt
  namespace: autoscaler-test
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      type: cx21
      sshKeys:
        - name: my-key
```

But the MD never gets ready:

```
% kubectl -n autoscaler-test get md as-hetzner-md -o json  | jq .status
{
  "conditions": [
    {
      "lastTransitionTime": "2023-11-16T11:25:04Z",
      "message": "Minimum availability requires 1 replicas, current 0 available",
      "reason": "WaitingForAvailableMachines",
      "severity": "Warning",
      "status": "False",
      "type": "Ready"
    },
    {
      "lastTransitionTime": "2023-11-16T11:25:04Z",
      "message": "Minimum availability requires 1 replicas, current 0 available",
      "reason": "WaitingForAvailableMachines",
      "severity": "Warning",
      "status": "False",
      "type": "Available"
    }
  ],
  "observedGeneration": 2,
  "phase": "ScalingUp",
  "replicas": 1,
  "selector": "cluster.x-k8s.io/cluster-name=autoscaler-test,nodepool=hetzner-worker-small",
  "unavailableReplicas": 1,
  "updatedReplicas": 1
}
```

But the node is ready:

```
% kubectl -n autoscaler-test get machine -o json | jq '.items[] | [.metadata.name,.status] '                     
[
  "as-hetzner-md-mvv6b-qjp97",
  {
    "addresses": [
      {
        "address": "91.107.216.134",
        "type": "ExternalIP"
      },
      {
        "address": "2a01:4f8:c010:8cc7::1",
        "type": "ExternalIP"
      }
    ],
    "bootstrapReady": true,
    "conditions": [
      {
        "lastTransitionTime": "2023-11-16T11:37:19Z",
        "status": "True",
        "type": "Ready"
      },
      {
        "lastTransitionTime": "2023-11-16T11:37:00Z",
        "status": "True",
        "type": "BootstrapReady"
      },
      {
        "lastTransitionTime": "2023-11-16T11:37:19Z",
        "status": "True",
        "type": "InfrastructureReady"
      },
      {
        "lastTransitionTime": "2023-11-16T11:37:19Z",
        "reason": "NodeProvisioning",
        "severity": "Warning",
        "status": "False",
        "type": "NodeHealthy"
      }
    ],
    "infrastructureReady": true,
    "lastUpdated": "2023-11-16T11:37:19Z",
    "observedGeneration": 3,
    "phase": "Provisioned"
  }
]
```

And up-and-running from the child cluster point of view too:

```
% kubectl --kubeconfig ~/.kube/autoscaler-test.conf get node
NAME                  STATUS     ROLES    AGE   VERSION
as-hetzner-mt-9fqjk   Ready      <none>   39m   v1.28.3+k0s
```

The only suspective thing I see is the fact that the CAPI `Machine` objects and the actual node names are different:

```
% kubectl get machine -n autoscaler-test                                 
NAME                        CLUSTER           NODENAME   PROVIDERID          PHASE         AGE   VERSION
as-hetzner-md-mvv6b-qjp97   autoscaler-test              hcloud://39439010   Provisioned   43m   v1.28.3

% kubectl --kubeconfig ~/.kube/autoscaler-test.conf get node       
NAME                  STATUS     ROLES    AGE   VERSION
as-hetzner-mt-9fqjk   Ready      <none>   41m   v1.28.3+k0s
```

Can this cause CAPI MD controller not to pick up nodes actually being ready?

While the child cluster and the nodes do work properly, this causes some un-desired side-effects such as an upgrade causing new `MachineSet` to be created but the old one is never scaled to zero. 

**What did you expect to happen:**

I'd expect the MachineDeployment just become ready when all the machines are running and marked as ready.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-hetzner version:  `v1.0.0-beta.26`
- Kubernetes version: `Server Version: v1.28.2`
- OS (e.g. from `/etc/os-release`):
