### ISSUE TITLE
support hcloud firewall

### ISSUE THREAD

**Issue by simonostendorf** [syself/cluster-api-provider-hetzner#1063]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I think it would be nice to add support for the HCloud Firewalls.
Inside the HetznerCluster you could specify the firewall(s) with a machine selector or with static/hardcoded IPs and ports.
This can be useful if you are using a hcloud cluster with public ips and want to control the access to the node-port services for example.

Example configuration inside the `HetznerCluster`:
```
spec:
  hcloudFirewalls:
    - name: example-api-in-with-selector
      assignment:
        labelSelector:
          machine_type: control_plane
      rules:
        in:
          - description: allow all cluster nodes to access port 6443 on all control-plane nodes
            port: 6443
            fromMachineSelector:
              caph-cluster-example: owned
    - name: example-node-port-in-with-fixed-ip
      assignment:
        labelSelector:
          machine_type: worker
      rules:
        in: 
          - description: allow two ip addresses to access node port services from worker nodes
            port: 30000-32767
            from:
              - 1.2.3.4/32
              - 5.6.7.8/32
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The above example should only be seen as example, I am open to discuss the implementation. 

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.26
- Kubernetes version: (use `kubectl version`) v1.28.3
- OS (e.g. from `/etc/os-release`): Flatcar Container Linux by Kinvolk 3602.2.1 (Oklo)
