### ISSUE TITLE
pre created LB

### ISSUE THREAD

**Issue by metanovii** [syself/cluster-api-provider-hetzner#1210]
Hi, I have a suggestion. You need to be able to transfer a pre-created load balancer ( via terraform for example ) to the controller, something like this:

```yaml
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    metadata:
      name: "${cluster_name}"
    spec:
      controlPlaneEndpoint:
        host: ""
        port: 443
      controlPlaneLoadBalancer:
        id(or name): super-puper-lb        <<<<<<<<<< here
      controlPlaneRegions:
      - fsn1
      hcloudNetwork:
        enabled: true
      hcloudPlacementGroups:
      - name: control-plane
        type: spread
      - name: md-0
        type: spread
      hetznerSecretRef:
        key:
          hcloudToken: token
          hetznerRobotPassword: robot-password
          hetznerRobotUser: robot-user
        name: hcloud
      sshKeys:
        hcloud:
        - name: terraform_k8s
  ```

This is necessary in order to install cilium. Now I have to divide the cluster deployment into two stages. First the cluster, then the cni.

**Comment by janiskemper** [comment]
I'm not sure whether I understand correctly. If you specify the name of the existing load balancer at the point where you marked it, then the cluster will use it!

**Comment by metanovii** [comment]
> I'm not sure whether I understand correctly. If you specify the name of the existing load balancer at the point where you marked it, then the cluster will use it!

It is wonderful. I'm going to try it, thanks!

**Comment by metanovii** [comment]
> I'm not sure whether I understand correctly. If you specify the name of the existing load balancer at the point where you marked it, then the cluster will use it!

Perhaps you misunderstood me. I'm talking about the balancer for k8s api. As I see, the provider has created a balancer specified in controlPlaneLoadBalancer.name, but not for the kubernetes api.

**Comment by metanovii** [comment]
My current config

```yaml
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    metadata:
      name: "${cluster_name}"
    spec:
      controlPlaneEndpoint:
        host: ""
        port: 443
      controlPlaneLoadBalancer:
        name: "hcloud-cluster-test-lb "
      controlPlaneRegions:
      - fsn1
      hcloudNetwork:
        enabled: true
      hcloudPlacementGroups:
      - name: control-plane
        type: spread
      - name: md-0
        type: spread
      hetznerSecretRef:
        key:
          hcloudToken: token
          hetznerRobotPassword: robot-password
          hetznerRobotUser: robot-user
        name: hcloud
      sshKeys:
        hcloud:
        - name: terraform_k8s
 ```
![image](https://github.com/syself/cluster-api-provider-hetzner/assets/9963998/ed347d34-7054-4091-b0bf-59fa01b558cb)
