### ISSUE TITLE
Multiple SSH key support for robot

### ISSUE THREAD

**Issue by ashish1099** [syself/cluster-api-provider-hetzner#1266]
/kind feature

I'm looking to add multiple ssh key which is added in robot key management.
I can only added 1 key which can be used to rescue boot and regular setup https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/topics/managing-ssh-keys.md#in-hetzner-robot

The idea is I want my engineers to login using their own ssh key

**Comment by batistein** [comment]
@ashish1099 the easiest way to do so right now is by using `kubectl debug node/<node-name> -it --image=<image name>`

**Comment by guettli** [comment]
caph implements the basic features to get a robust Kubernetes Cluster on Hetzner virtual machines and bare-metal.

I understand you use case. But is it part of the problem domain of caph?

You could run a daemonset which modifies /root/.ssh/authorized_keys easily. Here is an example:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-modifier-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: file-modifier
  template:
    metadata:
      labels:
        name: file-modifier
    spec:
      hostPID: true
      containers:
      - name: file-modifier
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo 'Hello, World!' >> /mnt/nodefile/data.txt"]
        volumeMounts:
        - name: nodefile
          mountPath: /mnt/nodefile
      volumes:
      - name: nodefile
        hostPath:
          path: /etc/nodefile
          type: DirectoryOrCreate
```

Of course the above snippet is just an example, but changing it to update `/root/.ssh/authorized_keys` should be doable.

@ashish1099 does this answer your question?
