### ISSUE TITLE
HetznerBaremetalHosts stuck in: host is still provisioning - state "registering"

### ISSUE THREAD

**Issue by thecodeassassin** [syself/cluster-api-provider-hetzner#1293]
/kind bug

**What steps did you take and what happened:**
Followed the guide here:

**What did you expect to happen:**

Kamaji Control plane + 2 bare metal hosts

**Anything else you would like to add:**

```bash
clusterctl -n europe-north describe cluster europe-north
NAME                                                   READY  SEVERITY  REASON                       SINCE  MESSAGE                                                                    
Cluster/europe-north                                   True                                          10m                                                                                
├─ClusterInfrastructure - HetznerCluster/europe-north  True                                          10m                                                                                
├─ControlPlane - KamajiControlPlane/europe-north                                                                                                                                        
└─Workers                                                                                                                                                                               
  ├─MachineDeployment/europe-north-baremetal           False  Warning   WaitingForAvailableMachines  11m    Minimum availability requires 2 replicas, current 0 available               
  │ └─2 Machines...                                    False  Info      StillProvisioning            10m    See europe-north-baremetal-c496z-2q8fz, europe-north-baremetal-c496z-9lw49  
  └─MachineDeployment/europe-north-cloud               True                                          11m                                                                                
(⎈ |management:default) stephen@stephen-laptop  ~/srv-folder/maxroll-media/k8s-edge-clusters/management-cluster   main ±  clusterctl -n europe-north describe cluster europe-north --show-conditions=all
NAME                                                   READY  SEVERITY  REASON                       SINCE  MESSAGE                                                                    
Cluster/europe-north                                   True                                          10m                                                                                
│           ├─ControlPlaneInitialized                  True                                          11m                                                                                
│           ├─ControlPlaneReady                        True                                          11m                                                                                
│           └─InfrastructureReady                      True                                          10m                                                                                
├─ClusterInfrastructure - HetznerCluster/europe-north  True                                          10m                                                                                
│             ├─ControlPlaneEndpointSet                True                                          11m                                                                                
│             ├─HCloudTokenAvailable                   True                                          11m                                                                                
│             ├─PlacementGroupsSynced                  True                                          11m                                                                                
│             ├─TargetClusterReady                     True                                          11m                                                                                
│             └─TargetClusterSecretReady               True                                          10m                                                                                
├─ControlPlane - KamajiControlPlane/europe-north                                                                                                                                        
│             ├─InfrastructureClusterPatched           True             Succeeded                    11m                                                                                
│             ├─KamajiControlPlaneIsInitialized        True             Succeeded                    11m                                                                                
│             ├─KamajiControlPlaneIsReady              True             Succeeded                    11m                                                                                
│             ├─KubeadmResourcesCreated                True             Succeeded                    11m                                                                                
│             ├─TenantControlPlaneAddressReady         True             Succeeded                    11m                                                                                
│             └─TenantControlPlaneCreated              True             Succeeded                    11m                                                                                
└─Workers                                                                                                                                                                               
  ├─MachineDeployment/europe-north-baremetal           False  Warning   WaitingForAvailableMachines  11m    Minimum availability requires 2 replicas, current 0 available               
  │ │           ├─Available                            False  Warning   WaitingForAvailableMachines  11m    Minimum availability requires 2 replicas, current 0 available               
  │ │           └─MachineSetReady                      False  Warning   ScalingUp                    11m    Scaling up MachineSet to 2 replicas (actual 0)                              
  │ └─2 Machines...                                    False  Info      StillProvisioning            10m    See europe-north-baremetal-c496z-2q8fz, europe-north-baremetal-c496z-9lw49  
  └─MachineDeployment/europe-north-cloud               True                                          11m                                                                                
                ├─Available                            True                                          11m          
```

**Environment:**

- cluster-api-provider-hetzner version: 
v1.0.0-beta.33

- Kubernetes version: (use `kubectl version`)
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.4+k3s1", GitCommit:"94e29e2ef5d79904f730e2024c8d1682b901b2d5", GitTreeState:"clean", BuildDate:"2024-04-25T17:33:09Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.25) and server (1.29) exceeds the supported minor version skew of +/-1
```

- OS (e.g. from `/etc/os-release`): 
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: europe-north-md-1
  namespace: europe-north
spec:
  template:
    spec:
      installImage:
        swraid: 1
        swraidLevel: 1
        image:
          path: /root/.oldroot/nfs/images/Ubuntu-2204-jammy-amd64-base.tar.gz
        partitions:
        - fileSystem: esp
          mount: /boot/efi
          size: 512M
        - fileSystem: ext4
          mount: /boot
          size: 1024M
        - fileSystem: ext4
          mount: /
          size: all
        postInstallScript: |
          #!/bin/bash
          mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
          cloud-init clean --logs
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: robot-ssh
```

Output of `go run github.com/guettli/check-conditions@latest all`
https://gist.github.com/thecodeassassin/71401f01d4da1b85929990b2a3b1ceee
