### ISSUE TITLE
support http healthcheck for api lb

### ISSUE THREAD

**Issue by simonostendorf** [syself/cluster-api-provider-hetzner#1339]
/kind feature

**Describe the solution you'd like**
I would like to use a http healthcheck for the api lb. This prevents the healthcheck to be ready before the apiserver itself is ready, because the port is opened before the apiserver is ready (and tcp healthcheck will be ready before apiserver is ready).

**Anything else you would like to add:**
Maybe this could be added like this:

```yaml
spec:
  controlPlaneLoadBalancer:
    healthcheck:
      type: http # (or tcp / https (http with tls enabled))
      interval: 15s
      timeout: 10s
      retries: 3
      domain: ""
      path: "/readyz"
```

if omitted use the hetzner default values (tcp, 15s interval, 10s timeout, 3 retries)
