### ISSUE TITLE
Deprovisioning Reconcile takes 26 seconds

### ISSUE THREAD

**Issue by guettli** [syself/cluster-api-provider-hetzner#1578]
/kind bug

This step took 26 seconds.

We do not want to Reconcile to take that long.

```yaml
level: INFO
time: "2025-04-02T15:04:45.884Z"
file: controllers/hetznerbaremetalhost_controller.go:93
message: Provisioning state changed
controller: hetznerbaremetalhost
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HetznerBareMetalHost
HetznerBareMetalHost:
  name: bm-e2e-1670788
  namespace: ci14221626200-6nzn0m
namespace: ci14221626200-6nzn0m
name: bm-e2e-1670788
reconcileID: dba5df91-5380-4b63-b38c-cac6a437e49a
HetznerCluster:
  name: ci14221626200-7qz3kn
  namespace: ci14221626200-6nzn0m
Cluster:
  name: ci14221626200-7qz3kn
  namespace: ci14221626200-6nzn0m
HetznerBareMetalMachine:
  name: ci14221626200-7qz3kn-control-plane-nzjdp
  namespace: ci14221626200-6nzn0m
from: deprovisioning
to: ""
```

```
level: INFO
time: "2025-04-02T15:04:45.884Z"
file: controllers/hetznerbaremetalhost_controller.go:76
message: Reconcile took too long
controller: hetznerbaremetalhost
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HetznerBareMetalHost
HetznerBareMetalHost:
  name: bm-e2e-1670788
  namespace: ci14221626200-6nzn0m
namespace: ci14221626200-6nzn0m
name: bm-e2e-1670788
reconcileID: dba5df91-5380-4b63-b38c-cac6a437e49a
HetznerCluster:
  name: ci14221626200-7qz3kn
  namespace: ci14221626200-6nzn0m
Cluster:
  name: ci14221626200-7qz3kn
  namespace: ci14221626200-6nzn0m
HetznerBareMetalMachine:
  name: ci14221626200-7qz3kn-control-plane-nzjdp
  namespace: ci14221626200-6nzn0m
duration: 26.031596
res:
  Requeue: true
  RequeueAfter: 0
reterr: null
```
