### ISSUE TITLE
Improve /docs/reference/hetzner-bare-metal-machine-template.md

### ISSUE THREAD

**Issue by pucilpet** [syself/cluster-api-provider-hetzner#209]
**Describe the solution you'd like**
/docs/reference/hetzner-bare-metal-machine-template.md and especially template.spec.hostSelector could probably use some references/examples.

Should we use GET/server object values from [hetzner webservice reference](https://robot.your-server.de/doc/webservice/en.html#server) for keys in the template.spec.hostSelector.matchExpressions.key ?

**Anything else you would like to add:**
I am also wondering whether there should be a cluster-template for HetznerBareMetalHost to make it clearer.

/kind proposal

**Comment by janiskemper** [comment]
Hi @pucilpet!
Quick answer to the hostSelcetor: You don't have to set it at all! You can use labels on your host and let a bm machine select a certain host by its labels. If not, then just any host is chosen. You see in the reference that the hostSelector is optional. You don't have to worry about it at all ;) 
Regarding the cluster template: Each host object has to be created in a highly specific way. We have described in the reference what fields have to be specified. We cannot create a cluster-template for this, as this wouldn't work out of the box. Everybody would have to adapt it. If you have another suggestion where we should have an example, then tell us! Here is a template, (which you have to adapt, of course):
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalHost
metadata:
  name: "bm-0"
spec:
  serverID: 1682566
  rootDeviceHints:
    wwn: "eui.0068475201b4egh2"
  maintenanceMode: false
  description: Test Machine 0
  ```
