### ISSUE TITLE
Private network for bare metal host / cloud hybrid

### ISSUE THREAD

**Issue by pucilpet** [syself/cluster-api-provider-hetzner#213]
/kind feature

**Describe the solution you'd like**
It is possible to link bare metal servers to the same private network as the cloud servers. I think it would be good to have an option for the private networking for hybrid clusters.

**Anything else you would like to add:**
More info: https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch/

Adding the vswitch is possible with the robot web service:
https://robot.your-server.de/doc/webservice/en.html#post-vswitch

**Comment by batistein** [comment]
This feature is not implemented yet. Since we had several problems with the private network in the past (very high ping, interruptions, etc.), we do not use it for our offers, so it has less prio from our side.
But I would love to see any contribution on it.

**Comment by shurshun** [comment]
Hi there! I would like to say thank you for such a handy product! I would also like to agree with the topic starter on the issue of private network support: we plan to order a set-up with a private network between servers (without the cloud) and, unfortunately, this is the only factor limiting the use of this provider :(

**Comment by batistein** [comment]
@mads-sogaard we didn't implemented the private network stuff on Hetzner Dedicated. In our production cluster we use the konnectivity-service, Cilium Host Firewall and run mTLS everywhere so we do not have the use case for private network. But of course anyone is welcome to contribute a PR.

**Comment by mstarostik** [comment]
I also figured the private networks aren't of that much use unless and until they offer more advanced routing setup between different private networks, NAT to public or the likes.
Anyway, one thing using a private network turned out to be still very useful to me is so I can get a known (private) IP for the API Server LB to pass as `k8sServiceHost` to Cilium when enabling its kube-proxy replacement. I'd be happy to simplify the setup some but haven't figured a way to pull the public IP for the LB into the ArgoCD app that provisions Cilium on newly created clusters.

**Comment by galiev** [comment]
> Cilium Host Firewall / Calico Global Network Policy are very convenient for host protection, but how to protect kube-apiserver, the main problem is that the api server does not support the proxy protocol and therefore I cannot restrict access. If you have any ideas I'll be very grateful.

the load in my cluster is minimal, so the following option suited me: TalosControlPlane + Cilium Host Firewall
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: tcp
spec:
  controlPlaneConfig:
    controlplane:
      configPatches:
      - op: add
        path: /machine/network
        value:
          interfaces:
          - dhcp: true
            interface: eth0
            vip:
              hcloud:
                apiToken: HCLOUD_TOKEN
              ip: x.x.x.x
      generateType: controlplane
      talosVersion: v1.4
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudMachineTemplate
    name: capihcmt-control-plane
  replicas: 3
  version: 1.27.2
```
