### ISSUE TITLE
cluster with baremetal host waiting for available machine

### ISSUE THREAD

**Issue by radimk** [syself/cluster-api-provider-hetzner#393]
/kind bug

I setup a cluster with BareMetalHost using hetzner-hcloud-control-planes flavor. My cluster template is edited to have 1 HCloudMachine for control plane, use CIDR bloks 10.243.0.0/16, zero replicas in `g-work-md-0` that would contain HCloud machine and 1 replica in `g-work-md-1` where bare metal is used. 
When the template is applied the CRs are created, machine for control-plane is added, its load-balancer too. Bare-metal server is reinstalled and it is up and running but not added to cluster. I also deployed CNI and CCM (Hetzner version).

**What did you expect to happen:**

The machine should join the cluster and KubeadmConfigTemplate/g-work-md-1 should run installation process there. Now the cluster is waiting for the machine because it thinks it is unhealthy

```
$ clusterctl describe cluster g-work
NAME                                                                       READY  SEVERITY  REASON                       SINCE  MESSAGE                                                       
Cluster/g-work                                                             True                                          51m                                                                   
├─ClusterInfrastructure - HetznerCluster/g-work                                                                                                                                                
├─ControlPlane - KubeadmControlPlane/g-work-control-plane                  True                                          51m                                                                   
│ └─Machine/g-work-control-plane-4gvd4                                     True                                          52m                                                                   
│   └─MachineInfrastructure - HCloudMachine/g-work-control-plane-4fxsc                                                                                                                         
└─Workers                                                                                                                                                                                      
  ├─MachineDeployment/g-work-md-0                                          True                                          54m                                                                   
  └─MachineDeployment/g-work-md-1                                          False  Warning   WaitingForAvailableMachines  54m    Minimum availability requires 1 replicas, current 0 available  
    └─Machine/g-work-md-1-5bd54bfd6c-tzxql                                 True                                          45m                                                                   
      └─MachineInfrastructure - HetznerBareMetalMachine/g-work-md-1-gh6ks                                                                             

$ kubectl describe MachineHealthCheck g-work-md-1-unhealthy-5m
...
Status:
  Conditions:
    Last Transition Time:  2022-11-03T07:49:57Z
    Status:                True
    Type:                  RemediationAllowed
  Expected Machines:       1
  Observed Generation:     1
  Targets:
    g-work-md-1-5bd54bfd6c-tzxql
Events:
  Type     Reason          Age                 From                           Message
  ----     ------          ----                ----                           -------
  Warning  ReconcileError  60m (x16 over 60m)  machinehealthcheck-controller  error creating client and cache for remote cluster: error fetching REST client config for remote cluster "default/g-work": failed to retrieve kubeconfig secret for Cluster default/g-work: secrets "g-work-kubeconfig" not found
  Warning  ReconcileError  59m (x2 over 59m)   machinehealthcheck-controller  error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster "default/g-work": client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: EOF

$ kubectl describe secrets g-work-kubeconfig
Name:         g-work-kubeconfig
Namespace:    default
Labels:       caph.environment=owned
              cluster.x-k8s.io/cluster-name=g-work
Annotations:  <none>

Type:  cluster.x-k8s.io/secret

Data
====
value:  5535 bytes

$ kubectl describe hetznerbaremetalmachines g-work-md-1-gh6ks
Name:         g-work-md-1-gh6ks
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=g-work
              cluster.x-k8s.io/deployment-name=g-work-md-1
              machine-template-hash=1681069827
              nodepool=g-work-md-1
Annotations:  cluster.x-k8s.io/cloned-from-groupkind: HetznerBareMetalMachineTemplate.infrastructure.cluster.x-k8s.io
              cluster.x-k8s.io/cloned-from-name: g-work-md-1
              infrastructure.cluster.x-k8s.io/HetznerBareMetalHost: default/bm-0
API Version:  infrastructure.cluster.x-k8s.io/v1beta1
Kind:         HetznerBareMetalMachine
...
Status:
  Addresses:
    Address:  46.4.66.173/26
    Type:     InternalIP
    Address:  2a01:4f8:140:2484::2/64
    Type:     InternalIP
    Address:  g-work-md-1-gh6ks
    Type:     Hostname
    Address:  g-work-md-1-gh6ks
    Type:     InternalDNS
  Conditions:
    Last Transition Time:  2022-11-03T07:49:58Z
    Status:                True
    Type:                  AssociateBMHCondition
    Last Transition Time:  2022-11-03T07:49:58Z
    Status:                True
    Type:                  InstanceBootstrapReady
    Last Transition Time:  2022-11-03T07:55:34Z
    Status:                True
    Type:                  InstanceReady
  Last Updated:            2022-11-03T07:51:34Z
  Ready:                   true
Events:                    <none>

```

**Anything else you would like to add:**

Configs related to bare-metal server. There is Ubuntu 22.04 image, hostSelector to match the host through added label. The machine is up and running and reachable with provided SSH key. No k8s packages and/or processes there though.

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: g-work-md-1
  namespace: default
spec:
  template:
    spec:
      installImage:
        image:
          path: /root/images/Ubuntu-2204-jammy-amd64-base.tar.gz
          # path: /root/.oldroot/nfs/install/../images/Ubuntu-2004-focal-64-minimal-hwe.tar.gz
        partitions:
        - fileSystem: ext4
          mount: /boot
          size: 1024M
        - fileSystem: ext4
          mount: /
          size: all
        postInstallScript: |
          #!/bin/bash
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
      hostSelector:
        matchExpressions:
        - key: "geneea/name"
          operator: "in"
          values:
          - "sigma"
          - "theta"
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: robot-ssh
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalHost
metadata:
  name: "bm-0"
  labels:
    geneea/name: "sigma"
spec:
  serverID: 1702753
  rootDeviceHints:
    raid:
      wwn:
        - "0x500a07511320714e"
        - "0x5002538d41d5de7c"
  maintenanceMode: false
  description: "sigma"
```

**Environment:**

- cluster-api-provider-hetzner version: ccm-hetzner-1.1.4 installed to workload cluster, ccm-hcloud-1.0.11 in management cluster
- Kubernetes version: (use `kubectl version`) 1.25.2
- OS (e.g. from `/etc/os-release`):
