### ISSUE TITLE
Apply custom labels to workload cluster nodes

### ISSUE THREAD

**Issue by rbjorklin** [syself/cluster-api-provider-hetzner#579]
/kind feature

**Describe the solution you'd like**
I would like to be able to apply my own custom labels on nodes in workload clusters. The use case I have in mind is using [Project Sveltos Classifiers](https://projectsveltos.github.io/sveltos/labels_management/) to apply different Cilium versions depending on which image is used.

**Anything else you would like to add:**
I've tried this but it doesn't seem to work:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: rbjorklin-com-control-plane
  namespace: rbjorklin-com
  labels:
    node.kubernetes.io/image: ubuntu-22.04
    environment: hcloud
spec:
  template:
    metadata:
      labels:
        role: control-plane
        node.kubernetes.io/image: ubuntu-22.04
    spec:
      imageName: ubuntu-22.04
      placementGroupName: control-plane
      type: cpx21
```

Sveltos Classifier:
```yaml
apiVersion: lib.projectsveltos.io/v1alpha1
kind: Classifier
metadata:
  name: cilium-old
spec:
  classifierLabels:
  - key: cilium
    value: v1-12-2
  deployedResourceConstraints:
  - group: ""
    version: v1
    kind: Node
    minCount: 1
    labelFilters:
    - key: node.kubernetes.io/image
      value: ubuntu-22.04
      operation: Equal
```

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.14
- Kubernetes version: 1.25.6
- OS (e.g. from `/etc/os-release`):
