### ISSUE TITLE
Subnet is created with same CIDR as Network

### ISSUE THREAD

**Issue by apricote** [syself/cluster-api-provider-hetzner#612]
/kind bug

**What steps did you take and what happened:**

Create a `HetznerCluster` with following (partial) settings:

```yaml
spec:
  hcloudNetwork:
    enabled: true
    networkZone: eu-central
    cidrBlock: 10.0.0.0/8
    subnetCidrBlock: 10.0.0.0/24
```

Observe that a Network with CIDR `10.0.0.0/8` is created. Also observe that this Network has one subnet with CIDR `10.0.0.0/8`.

**What did you expect to happen:**

I expected the subnet to be `10.0.0.0/24` instead.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-hetzner version: `v1.0.0-beta.14`
- Kubernetes version: Client `v1.26.1`, bootstrap cluster `v1.25.2`, workload cluster `v1.26.1`
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04 on cluster, Arch Linux locally.
