### ISSUE TITLE
How to customize flavor

### ISSUE THREAD

**Issue by rgzr** [syself/cluster-api-provider-hetzner#635]
/kind feature

**Describe the solution you'd like**
I am using hcloud-network flavor, but I would like to apply further customization to the generated cluster yaml.

Specifically, I would like to apply this patch:

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  controlPlaneEndpoint:
    host: "${SUBDOMAIN_CONTROL_PLANE}.${DOMAIN_BASE}"
    port: 443
  controlPlaneLoadBalancer:
    enabled: false
```

So the control plane loadbalancer is disabled and I specify a host for the controlplane (providing the environment variables).

What is the recommended way of doing this? Creating a custom template seems overkill as I only want to override some values.

Manually updating the generated cluster yaml is possible but I would like to automate that and I am not sure of the best way to do this (sure I am missing something).

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.14
- Kubernetes version: client 1.26.1
- OS (e.g. from `/etc/os-release`):
