### ISSUE TITLE
The hybrid cluster is in ready state and fully initialized but `MachineHealthCheck` are failed

### ISSUE THREAD

**Issue by Stringls** [syself/cluster-api-provider-hetzner#714]
/kind bug

**What steps did you take and what happened:**

*What I have*
I try to create a hybrid cluster (CP - VM, MD - BM) with private network feature ON. I know it's not supported yet, so I tried to use another [Hetzner CCM ](https://github.com/identw/hetzner-cloud-controller-manager). The original `deploy.yaml` is a bit out of date so I updated it and changed the `dnsPolicy` to **Default**, also added one more toleration to deployment to deploy a CCM controller onto CP. In the result nodes are fully initialized with no issues, they are synced, registered. MD nodes have no taints and I am able to deploy any pods on it.

*What happens*

CAPI thinks nodes (**BOTH** CP and MD) are unhealthy and does not mark them as healthy. I cannot find logs/into why it's not healthy and since they are unhealthy rebooting happens to my MD, since there is only 1 CP.

**What did you expect to happen:**

I expected CAPI to mark nodes as initalized/healthy.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Communication between nodes **are happenning**. I deployed `dnsutils` pods to each node (CP and MD) and tried to ping another pod by its IP *10...*. The ping is working from both sides with latency about 25ms. so communication is there.
Here are some logs/info:
*List of all pods*
```
NAMESPACE     NAME                                                     READY   STATUS    RESTARTS   AGE
kube-system   cilium-fnvt2                                             1/1     Running   0          13m
kube-system   cilium-ftcd8                                             1/1     Running   0          6m33s
kube-system   cilium-operator-7964c7b4d6-4slf8                         1/1     Running   0          13m
kube-system   coredns-6d4b75cb6d-hxhlj                                 1/1     Running   0          14m
kube-system   coredns-6d4b75cb6d-s2hbx                                 1/1     Running   0          14m
kube-system   etcd-hetzner-bm-control-plane-k4gqz                      1/1     Running   0          14m
kube-system   hetzner-cloud-controller-manager-7959845f55-h5s8g        1/1     Running   0          7m8s
kube-system   hubble-relay-6dc5f44ff5-6nrsj                            1/1     Running   0          13m
kube-system   hubble-ui-ccb8c4cd8-rkhqk                                2/2     Running   0          13m
kube-system   kube-apiserver-hetzner-bm-control-plane-k4gqz            1/1     Running   0          14m
kube-system   kube-controller-manager-hetzner-bm-control-plane-k4gqz   1/1     Running   0          14m
kube-system   kube-proxy-95f6w                                         1/1     Running   0          14m
kube-system   kube-proxy-jjnsz                                         1/1     Running   0          6m33s
kube-system   kube-scheduler-hetzner-bm-control-plane-k4gqz            1/1     Running   0          14m
```

*Hetzner CCM logs*
```
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
I0330 08:47:08.678921       1 serving.go:348] Generated self-signed cert in-memory
W0330 08:47:15.879857       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0330 08:47:15.972465       1 controllermanager.go:143] Version: v0.0.0-master+$Format:%H$
Hetzner Cloud k8s cloud controller v0.0.8 started
I0330 08:47:15.977589       1 secure_serving.go:210] Serving securely on [::]:10258
I0330 08:47:15.978193       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0330 08:47:16.572413       1 node_lifecycle_controller.go:77] Sending events to api server
I0330 08:47:16.572957       1 controllermanager.go:291] Started "cloud-node-lifecycle"
I0330 08:47:16.573592       1 controllermanager.go:291] Started "service"
W0330 08:47:16.573624       1 core.go:111] --configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
W0330 08:47:16.573638       1 controllermanager.go:279] Skipping "route"
I0330 08:47:16.573971       1 node_controller.go:118] Sending events to api server.
I0330 08:47:16.574139       1 controllermanager.go:291] Started "cloud-node"
I0330 08:47:16.575798       1 controller.go:233] Starting service controller
I0330 08:47:16.576257       1 shared_informer.go:255] Waiting for caches to sync for service
I0330 08:47:16.576666       1 node_controller.go:157] Waiting for informer caches to sync
I0330 08:47:16.770785       1 node_controller.go:406] Initializing node hetzner-bm-control-plane-k4gqz with cloud provider
I0330 08:47:16.777569       1 shared_informer.go:262] Caches are synced for service
I0330 08:47:18.587976       1 node_controller.go:470] Successfully initialized node hetzner-bm-control-plane-k4gqz with cloud provider
I0330 08:47:18.588612       1 event.go:294] "Event occurred" object="hetzner-bm-control-plane-k4gqz" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0330 08:47:27.221366       1 node_controller.go:406] Initializing node bm-hetzner-bm-md-1-r9zhl with cloud provider
I0330 08:47:29.071365       1 node_controller.go:470] Successfully initialized node bm-hetzner-bm-md-1-r9zhl with cloud provider
I0330 08:47:29.071946       1 event.go:294] "Event occurred" object="bm-hetzner-bm-md-1-r9zhl" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
```

*MD events and conditions*
```
Events:
  Type    Reason                   Age                From                   Message
  ----    ------                   ----               ----                   -------
  Normal  Starting                 12m                kube-proxy             
  Normal  NodeHasSufficientMemory  12m (x8 over 13m)  kubelet                Node bm-hetzner-bm-md-1-r9zhl status is now: NodeHasSufficientMemory
  Normal  RegisteredNode           12m                node-controller        Node bm-hetzner-bm-md-1-r9zhl event: Registered Node bm-hetzner-bm-md-1-r9zhl in Controller
  Normal  Synced                   12m                cloud-node-controller  Node synced successfully

Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Thu, 30 Mar 2023 11:47:50 +0300   Thu, 30 Mar 2023 11:47:50 +0300   CiliumIsUp                   Cilium is running on this node
  MemoryPressure       False   Thu, 30 Mar 2023 11:58:32 +0300   Thu, 30 Mar 2023 11:47:27 +0300   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 30 Mar 2023 11:58:32 +0300   Thu, 30 Mar 2023 11:47:27 +0300   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 30 Mar 2023 11:58:32 +0300   Thu, 30 Mar 2023 11:47:27 +0300   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 30 Mar 2023 11:58:32 +0300   Thu, 30 Mar 2023 11:47:47 +0300   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```

*CP events and conditions*
```
Events:
  Type     Reason                   Age                From                   Message
  ----     ------                   ----               ----                   -------
  Normal   Starting                 20m                kube-proxy             
  Normal   NodeAllocatableEnforced  21m                kubelet                Updated Node Allocatable limit across pods
  Normal   Starting                 21m                kubelet                Starting kubelet.
  Warning  InvalidDiskCapacity      21m                kubelet                invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  21m (x4 over 21m)  kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    21m (x4 over 21m)  kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     21m (x3 over 21m)  kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasSufficientPID
  Normal   Starting                 20m                kubelet                Starting kubelet.
  Normal   RegisteredNode           20m                node-controller        Node hetzner-bm-control-plane-k4gqz event: Registered Node hetzner-bm-control-plane-k4gqz in Controller
  Warning  InvalidDiskCapacity      20m                kubelet                invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  20m                kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    20m                kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     20m                kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  20m                kubelet                Updated Node Allocatable limit across pods
  Normal   NodeReady                19m                kubelet                Node hetzner-bm-control-plane-k4gqz status is now: NodeReady
  Normal   Synced                   12m                cloud-node-controller  Node synced successfully

Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Thu, 30 Mar 2023 11:40:34 +0300   Thu, 30 Mar 2023 11:40:34 +0300   CiliumIsUp                   Cilium is running on this node
  MemoryPressure       False   Thu, 30 Mar 2023 11:57:19 +0300   Thu, 30 Mar 2023 11:39:56 +0300   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 30 Mar 2023 11:57:19 +0300   Thu, 30 Mar 2023 11:39:56 +0300   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 30 Mar 2023 11:57:19 +0300   Thu, 30 Mar 2023 11:39:56 +0300   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 30 Mar 2023 11:57:19 +0300   Thu, 30 Mar 2023 11:40:29 +0300   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```

*clusterctl logs* - CP is all true for the first 20 mins while MD is not true at all
```
NAME                                                                           READY  SEVERITY  REASON                                                       SINCE  MESSAGE                                                        
Cluster/hetzner-bm                                                             False  Warning   NodeStartupTimeout @ Machine/hetzner-bm-control-plane-rwrnn  5m59s  Node failed to report startup in 20m0s                          
│           ├─ControlPlaneInitialized                                          True                                                                          26m                                                                    
│           ├─ControlPlaneReady                                                False  Warning   NodeStartupTimeout @ Machine/hetzner-bm-control-plane-rwrnn  5m59s  Node failed to report startup in 20m0s                          
│           └─InfrastructureReady                                              True                                                                          28m                                                                    
├─ClusterInfrastructure - HetznerCluster/hetzner-bm                                                                                                                                                                                 
│             ├─LoadBalancerAttached                                           True                                                                          28m                                                                    
│             ├─NetworkAttached                                                True                                                                          28m                                                                    
│             └─PlacementGroupsSynced                                          True                                                                          28m                                                                    
├─ControlPlane - KubeadmControlPlane/hetzner-bm-control-plane                  False  Warning   NodeStartupTimeout @ Machine/hetzner-bm-control-plane-rwrnn  5m59s  Node failed to report startup in 20m0s                          
│ │           ├─Available                                                      True                                                                          26m                                                                    
│ │           ├─CertificatesAvailable                                          True                                                                          28m                                                                    
│ │           ├─MachinesCreated                                                True                                                                          28m                                                                    
│ │           ├─MachinesReady                                                  False  Warning   NodeStartupTimeout @ Machine/hetzner-bm-control-plane-rwrnn  5m59s  Node failed to report startup in 20m0s                          
│ │           └─Resized                                                        True                                                                          27m                                                                    
│ └─Machine/hetzner-bm-control-plane-rwrnn                                     False  Warning   NodeStartupTimeout                                           6m2s   Node failed to report startup in 20m0s                          
│   │           ├─BootstrapReady                                               True                                                                          28m                                                                    
│   │           ├─HealthCheckSucceeded                                         False  Warning   NodeStartupTimeout                                           6m2s   Node failed to report startup in 20m0s                          
│   │           ├─InfrastructureReady                                          True                                                                          28m                                                                    
│   │           ├─NodeHealthy                                                  False  Warning   NodeProvisioning                                             26m                                                                    
│   │           └─OwnerRemediated                                              False  Warning   WaitingForRemediation                                        6m2s   KCP can't remediate if current replicas are less or equal to 1  
│   └─MachineInfrastructure - HCloudMachine/hetzner-bm-control-plane-k4gqz                                                                                                                                                          
│                 ├─InstanceBootstrapReady                                     True                                                                          28m                                                                    
│                 └─InstanceReady                                              True                                                                          28m                                                                    
└─Workers                                                                                                                                                                                                                           
  ├─MachineDeployment/hetzner-bm-md-0                                          True                                                                          29m                                                                    
  │             └─Available                                                    True                                                                          29m                                                                    
  └─MachineDeployment/hetzner-bm-md-1                                          False  Warning   WaitingForAvailableMachines                                  29m    Minimum availability requires 1 replicas, current 0 available   
    │           └─Available                                                    False  Warning   WaitingForAvailableMachines                                  29m    Minimum availability requires 1 replicas, current 0 available   
    └─Machine/hetzner-bm-md-1-9c499ff98-4sb5w                                  True                                                                          18m                                                                    
      │           ├─BootstrapReady                                             True                                                                          25m                                                                    
      │           ├─InfrastructureReady                                        True                                                                          18m                                                                    
      │           └─NodeHealthy                                                False  Warning   NodeProvisioning                                             18m                                                                    
      └─MachineInfrastructure - HetznerBareMetalMachine/hetzner-bm-md-1-r9zhl                                                                                                                                                       
                    ├─AssociateBMHCondition                                    True                                                                          25m                                                                    
                    ├─InstanceBootstrapReady                                   True                                                                          25m                                                                    
                    └─InstanceReady                                            True                                                                          18m                                                                    
                                                                                                                                    
```

**Environment:**

- cluster-api-provider-hetzner version: 1.0.0-beta.12
- Kubernetes version: (use `kubectl version`) 1.24.1
- OS (e.g. from `/etc/os-release`): CP - ubuntu 22.04, MD - ubuntu 20.04 focal x64 minimal hwe

**Comment by janiskemper** [comment]
From the README of the CCM you used:
>Note: Unlike the original [controller](https://github.com/hetznercloud/hcloud-cloud-controller-manager) this controller does not support [Hetzner Cloud Networks](https://community.hetzner.com/tutorials/hcloud-networks-basic) since it is not technically possible to implement this. Read more in the [why there is no support for hetzner cloud networks](https://github.com/identw/hetzner-cloud-controller-manager#why-there-is-no-support-for-hetzner-cloud-networks). For a network in your cluster consisting of cloud and dedicated servers, you should use some cni plugin that will build an overlay network between servers. For example [kube-router](https://github.com/cloudnativelabs/kube-router) with --enable-overlay enabled or [cilium](https://cilium.io/) with tunnel: vxlan or tunnel: geneve. If you require [Hetzner Cloud Networks](https://community.hetzner.com/tutorials/hcloud-networks-basic) then you should use the original [controller](https://github.com/hetznercloud/hcloud-cloud-controller-manager) and refuse to use dedicated servers in your cluster.

Doesn't this state that what you tried won't work anyway?

**Comment by Stringls** [comment]
> From the README of the CCM you used:
> 
> > Note: Unlike the original [controller](https://github.com/hetznercloud/hcloud-cloud-controller-manager) this controller does not support [Hetzner Cloud Networks](https://community.hetzner.com/tutorials/hcloud-networks-basic) since it is not technically possible to implement this. Read more in the [why there is no support for hetzner cloud networks](https://github.com/identw/hetzner-cloud-controller-manager#why-there-is-no-support-for-hetzner-cloud-networks). For a network in your cluster consisting of cloud and dedicated servers, you should use some cni plugin that will build an overlay network between servers. For example [kube-router](https://github.com/cloudnativelabs/kube-router) with --enable-overlay enabled or [cilium](https://cilium.io/) with tunnel: vxlan or tunnel: geneve. If you require [Hetzner Cloud Networks](https://community.hetzner.com/tutorials/hcloud-networks-basic) then you should use the original [controller](https://github.com/hetznercloud/hcloud-cloud-controller-manager) and refuse to use dedicated servers in your cluster.
> 
> Doesn't this state that what you tried won't work anyway?

Yeah, it means, but how the nodes are communicating then? It seems it's in working state, but the health checks are failed. I am trying to understand why it's failing.

1. When I use your Hetzner CCM fork it gives `dial tcp: lookup bm-hetzner-bm-md-1-bzjkb on 1.1.1.1:53: no such host`
2. When I use the CCM I mentioned it does not give the error about DNS name resolution, even when I use private network over cluster.

So my questions are:
1. How the healthchecks in CAPI Hetzner are working, what the requirements of health check are (because all the conditions nodes are satisfying as you can see based on conditions of the nodes)?
2. I see that I can use cillium tunnel, but that means I need to remove private network anyway, am I right?

**Comment by janiskemper** [comment]
to 2.: Yes that sounds like this to me. And that also corresponds to my existing knowledge about this topic. As you stated at the beginning, it is not supported .
to 1: We use in our CCM (https://github.com/syself/hetzner-cloud-controller-manager), which also supports Hetzner robot prefixes of the nodes. As they are required, no CCM will work that doesn't use these prefixes probably.

**Comment by Stringls** [comment]
> to 1: We use in our CCM (https://github.com/syself/hetzner-cloud-controller-manager), which also supports Hetzner robot prefixes of the nodes. As they are required, no CCM will work that doesn't use these prefixes probably.

Where I am able:
* to check these prefixes
* to check if the prefixes in Hetzner Robot matches with prefixes of the nodes in the cluster? In other words, where to find these prefixes in the cluster? Is `hcloud://29978` a prefix?

**Comment by janiskemper** [comment]
`hcloud://bm-29978` would be a bare metal server

**Comment by janiskemper** [comment]
But the CCM that you used does the same thing that our CCM does AFAIK.. I don't see how you would get any benefit from using it (only that you face the issue with prefixes)

**Comment by Stringls** [comment]
> But the CCM that you used does the same thing that our CCM does AFAIK.. I don't see how you would get any benefit from using it (only that you face the issue with prefixes)

The CCM I used is synchronizing the cluster at least and I am able to work with it if I remove `MachineHealthCheck` or increase the remediation timeout :)

**Comment by janiskemper** [comment]
But it doesn't work with private networks either as it is stated in the README. So what do you try to do that works with it and doesn't work with the other CCM?

**Comment by janiskemper** [comment]
If I understand that then I think I'd be able to help you better ;)

**Comment by Stringls** [comment]
> But it doesn't work with private networks either as it is stated in the README. So what do you try to do that works with it and doesn't work with the other CCM?

I deploy a CAPI Hetzner cluster with flavor `hcloud-control-plane` and with `hcloudNetwork.enabled=true` value. 1 CP and 1 MD - baremetal. Kubernetes version 1.24.1. I deploy the below CCM.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hetzner-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hetzner-cloud-controller-manager
  template:
    metadata:
      labels:
        app: hetzner-cloud-controller-manager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ccm-ccm-hetzner
      serviceAccountName: ccm-ccm-hetzner
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
            - weight: 1
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        # this taint is set by all kubelets running `--cloud-provider=external`
        # so we should tolerate it to schedule the cloud controller manager
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        # cloud controller manages should be able to run on masters
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
        - key: "node.kubernetes.io/not-ready"
          effect: "NoSchedule"
      containers:
        - image: ghcr.io/identw/hetzner-cloud-controller-manager:v0.0.9
          name: hetzner-cloud-controller-manager
          args:
            - "--cloud-provider=hetzner"
            - "--leader-elect=false"
            - "--allow-untagged-cloud"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsUser: 40801
            runAsGroup: 40801
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hetzner
                  key: hcloud
            - name: HROBOT_USER
              valueFrom:
                secretKeyRef:
                  name: hetzner
                  key: robot-user
            - name: HROBOT_PASS
              valueFrom:
                secretKeyRef:
                  name: hetzner
                  key: robot-password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccm-ccm-hetzner
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ccm-ccm-hetzner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ccm-ccm-hetzner
    namespace: kube-system
```

I've just noticed the deployment is not getting `network` key from the `hetzner` secret as official Heztner CCM docs says to do. So I suppose that's why it's working?
To be honest, I do not understand why it' working and other CCMs are not
