### ISSUE TITLE
Support Shared vCPU (Arm64) HCloud server types

### ISSUE THREAD

**Issue by stubbi** [syself/cluster-api-provider-hetzner#786]
***Goals***
Support Shared vCPU (Arm64) Hcloud [server types](https://www.hetzner.com/cloud).

**User Story**

As a user I would like to provision the new Hetzner CAX machine types `CAX11`, `CAX21`, `CAX31`, and `CAX41`

**Detailed Description**

I'd like to be able to set the `spec.template.spec.type` of `HCloudMachineTemplate` to one of the values mentioned above.

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: control-plane
      type: cx31
``` 

Currently, doing so results the following error message

```
Error from server (Invalid): error when creating "my-clusteryaml": HCloudMachineTemplate.infrastructure.cluster.x-k8s.io "my-cluster-control-plane" is invalid: spec.template.spec.type: Unsupported value: "CAX11": supported values: "cpx11", "cx21", "cpx21", "cx31", "cpx31", "cx41", "cpx41", "cx51", "cpx51", "ccx11", "ccx12", "ccx21", "ccx22", "ccx31", "ccx32", "ccx41", "ccx42", "ccx51", "ccx52", "ccx62", "cax11", "cax21", "cax31", "cax41"
```

/kind proposal
