### ISSUE TITLE
cluster autoscaler from zero

### ISSUE THREAD

**Issue by Menosc** [syself/cluster-api-provider-hetzner#790]
/kind bug

**What steps did you take and what happened:**
Hi, we are using a hybrid setup of a workload cluster, where we have both baremetal server as a worker node and hcloud control plane. And we wanted to setup CAPI provider cluster autoscaler with an option of scaling from 0. We have created separate machinedeployment with 0 replicas for autoscaler to spin up workers. 
Referring to [this PR](https://github.com/syself/cluster-api-provider-hetzner/pull/272), this feature should be available.

Issue: it doesn't scale from zero, but when this machinedeployment has at least one replica, it can scale it up and down(to zero)

**What did you expect to happen:**
Scaling up from zero

**Environment:**

- cluster-api-provider-hetzner version: v1.0.0-beta.16
- Kubernetes version on the management cluster on GKE: v1.25.7
- Kubernetes version on the workload cluster on hetzner:  v1.25.2
- OS: Ubuntu 22.04

**codebase:** 
 
 1) machinedeployment: 
 
 ```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"
    machinedeployment.clusters.x-k8s.io/revision: "1"
    meta.helm.sh/release-name: hetzner-bm-cluster
    meta.helm.sh/release-namespace: ###
  labels:
    app.kubernetes.io/managed-by: Helm
    cluster.x-k8s.io/cluster-name: hetzner-bm-cluster
    helm.toolkit.fluxcd.io/name: hetzner-bm-cluster
    helm.toolkit.fluxcd.io/namespace: default
    node.kubernetes.io/instance-type: CX21
    nodepool: hetzner-bm-cluster-md-0
    color: green
  name: hetzner-bm-cluster-md-0
  namespace: ###
spec:
  clusterName: hetzner-bm-cluster
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: hetzner-bm-cluster
      cluster.x-k8s.io/deployment-name: hetzner-bm-cluster-md-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: hetzner-bm-cluster
        cluster.x-k8s.io/deployment-name: hetzner-bm-cluster-md-0
        nodepool: hetzner-bm-cluster-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: hetzner-bm-cluster-md-0
      clusterName: hetzner-bm-cluster
      failureDomain: fsn1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: hetzner-bm-cluster-md-0
      version: v1.25.2
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2023-04-26T12:51:42Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-04-26T12:51:42Z"
    status: "True"
    type: Available
  observedGeneration: 9
  phase: Running
  readyReplicas: 0
  replicas: 0
  selector: cluster.x-k8s.io/cluster-name=hetzner-bm-cluster,cluster.x-k8s.io/deployment-name=hetzner-bm-cluster-md-0
  unavailableReplicas: 0
  updatedReplicas: 0
```
2) HCloudMachineTemplate: 

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  annotations:
    meta.helm.sh/release-name: hetzner-bm-cluster
    meta.helm.sh/release-namespace: ###
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: hetzner-bm-cluster
    helm.toolkit.fluxcd.io/namespace: default
  name: hetzner-bm-cluster-md-0
  namespace: ###
spec:
  template:
    spec:
      imageName: ubuntu-22.04
      placementGroupName: md-0
      type: cx21
```
3) logs from autoscaler pod
when 1 replica exists:
```
I0426 11:49:35.264075       1 flags.go:57] FLAG: --node-group-auto-discovery="[clusterapi:color=green]"
I0426 12:46:11.268080       1 clusterapi_provider.go:67] discovered node group: MachineDeployment/###/hetzner-bm-cluster-md-0 (min: 0, max: 3, replicas: 1)
```
when 0 replicas: 
```
I0426 14:55:15.901061       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-deployment", APIVersion:"v1", ResourceVersion:"22944360", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up: 
```

4) autoscaler config (runs from the management cluster) :

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: ###
  labels:
    app: cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
       - image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.25.1
         name: cluster-autoscaler
         resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
         command:
          - ./cluster-autoscaler
          - --cloud-provider=clusterapi
          - --nodes=1:10:CX21:FSN1:hetzner-bm-cluster-md-0
          - --v=4
          - --kubeconfig=/etc/bm-kubeconfig/value
          - --clusterapi-cloud-config-authoritative
          - --node-group-auto-discovery=clusterapi:color=green
          - --scan-interval=1m
         volumeMounts:
          - name: bm-kubeconfig
            mountPath: /etc/bm-kubeconfig
            readOnly: true
      volumes:
        - name: bm-kubeconfig
          secret:
            secretName: hetzner-bm-cluster-kubeconfig
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    resources:
    - hcloudmachinetemplates
    verbs:
    - get
    - list
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: ###
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: ###
```
