### ISSUE TITLE
Inability to provision Cluster with an externally managed Control Plane

### ISSUE THREAD

**Issue by prometherion** [syself/cluster-api-provider-hetzner#845]
/kind bug

**What steps did you take and what happened:**

Try to create an `HetznerCluster`  resource with the following manifest:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: workload
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    enabled: false
  controlPlaneRegions: []
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
  - name: md-0
    type: spread
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
    name: hetzner
  sshKeys:
    hcloud:
    - name: REDACTED
```

Getting the following error:

```
The HetznerCluster "workload" is invalid: 
* spec.controlPlaneRegions: Invalid value: []v1beta1.Region{}: control plane regions must not be empty
* spec.controlPlaneEndpoint: Invalid value: :443: controlPlaneEndpoint has to be specified if controlPlaneLoadBalancer is not enabled
```

**What did you expect to happen:**

The said `Cluster` is referencing an externally managed Control Plane thanks to [Kamaji](https://kamaji.clastix.io).

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: workload
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KamajiControlPlane
    name: workload-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: workload
```

Kamaji is offering a [CAPI Control Plane provider](https://github.com/clastix/cluster-api-control-plane-provider-kamaji) which is responsible for creating the required Control Plane endpoint, and then patching it back to the provided Infrastructure Provider.

Cluster API contract allows specifying an externally managed Control Plane, by not giving for granted it must be on the same infrastructure provider as per VM/machine.

My original plan was to take advantage of the `HetznerClusters.spec.controlPlaneLoadBalancer.enabled` field set to `false`, however, with the said error, I'm confused about how it should be used.

My expectation would be delegating the provisioning of the Control Plane provider (in this case, Kamaji) in getting the required address and offloading to the Kamaji CP Provider to patch the `HetznerClusters` resource with the IP address.

> This is the pattern we agreed with several other providers, such as:
> - CAPO (OpenStack)
> - KubeVirt
> - Metal3
> - Equinix

**Anything else you would like to add:**

N.R.

**Environment:**

- cluster-api-provider-hetzner version: caph:v1.0.0-beta.17
- Kubernetes version: v1.25.2
- OS (e.g. from `/etc/os-release`):  N.R.
